const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.ScriptsInEvents.FolhaDeEventos3_Event19_Act2
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chão: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Fixar: 0},
	{jogador1: 0},
	{trap: 0},
	{Senóide: 0},
	{inimigo: 0},
	{Vitoria: 0},
	{TextoFim: 0},
	{Botão: 0},
	{jogadorAni: 0},
	{Teclado: 0},
	{Sprite2: 0},
	{Diamante: 0},
	{Pontos: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sprite: 0},
	{chão2: 0},
	{jogador2: 0},
	{trap2: 0},
	{Inimigo2: 0},
	{Texto: 0},
	{Botão2: 0},
	{JogadorAnim2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Forma3D: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Botão3: 0},
	{Texto2: 0},
	{Texto3: 0},
	{txtvidas: 0},
	{txtvidas2: 0},
	{Texto4: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Botão4: 0},
	{Toque: 0},
	{pontoss: 0},
	{Pontossss: 0},
	{Vidas: 0},
	{pontos: 0},
	{Pontosss: 0}
];

self.InstanceType = {
	chão: class extends self.ISpriteInstance {},
	jogador1: class extends self.ISpriteInstance {},
	trap: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Vitoria: class extends self.ISpriteInstance {},
	TextoFim: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	jogadorAni: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Diamante: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chão2: class extends self.ISpriteInstance {},
	jogador2: class extends self.ISpriteInstance {},
	trap2: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Botão2: class extends self.IButtonInstance {},
	JogadorAnim2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Forma3D: class extends self.I3DShapeInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Botão3: class extends self.IButtonInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	txtvidas: class extends self.ITextInstance {},
	txtvidas2: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Botão4: class extends self.IButtonInstance {},
	Toque: class extends self.IInstance {},
	pontoss: class extends self.ITextInstance {},
	Pontossss: class extends self.ITextInstance {}
}